Repository cardano-scaling/hydra, pull requests merged in 2023-05, with the labels that each got.

#838 Hydra-node architecture
  docs/adr/2021-10-23_010-use-direct-chain.md
  docs/adr/2022-03-28_017-udp-networking.md
  docs/benchmarks/index.md
  docs/core-concepts/architecture/architecture-c4.puml
  docs/core-concepts/architecture/hydra-components.svg
  docs/core-concepts/architecture/hydra-pull-based-network.jpg
  docs/core-concepts/architecture/index.md
  docs/core-concepts/architecture/networking.md
  docs/core-concepts/behavior.md
  docs/core-concepts/index.md
  docs/core-concepts/layer-two.md
  docs/core-concepts/rollbacks/_category_.json
  docs/docs/haskell_packages.md
  docs/docusaurus.config.js
  docs/i18n/ja/docusaurus-plugin-content-docs-benchmarks/current/index.md
  docs/i18n/ja/docusaurus-plugin-content-docs-core-concepts/current/index.md
  docs/i18n/ja/docusaurus-plugin-content-docs-topologies/current/index.md
  docs/package.json
  docs/scripts/regenerate-plantuml.sh
  docs/src/css/custom.css
  docs/topologies/index.md
  docs/use-cases/index.md
  docs/yarn.lock
  hydra-node/images/hydra-architecture-direct.jpg
  hydra-node/images/hydra-architecture-direct_800x.jpg
  hydra-node/src/Hydra/Node.hs
  nix/hydra/shell.nix
Labels: documentation :book:

#859 Increase signal to noise ratio in logs
  CHANGELOG.md
  hydra-node/exe/hydra-node/Main.hs
  hydra-node/golden/HydraNodeLog SimpleTx.json
  hydra-node/hydra-node.cabal
  hydra-node/json-schemas/logs.yaml
  hydra-node/src/Hydra/Logging/Monitoring.hs
  hydra-node/src/Hydra/Network/Ouroboros.hs
  hydra-node/src/Hydra/Node.hs
  hydra-node/src/Hydra/Node/EventQueue.hs
  hydra-node/test/Hydra/API/ServerSpec.hs
  hydra-node/test/Hydra/BehaviorSpec.hs
  hydra-node/test/Hydra/Logging/MonitoringSpec.hs
  hydra-node/test/Hydra/Model/MockChain.hs
  hydra-node/test/Hydra/Node/EventQueueSpec.hs
  hydra-node/test/Hydra/NodeSpec.hs
Labels: task, ux

#876 Add operating node section to the documentation
  docs/docs/getting-started/operating-hydra.md
Labels: documentation :book:, ux
