Repository cardano-scaling/hydra, pull requests merged in 2024-10, with the labels that each got.

#1690 Fix handling of reward redeemers on commit transaction
  CHANGELOG.md
  hydra-cardano-api/hydra-cardano-api.cabal
  hydra-cardano-api/src/Hydra/Cardano/Api.hs
  hydra-cardano-api/src/Hydra/Cardano/Api/StakeAddress.hs
  hydra-node/test/Hydra/Chain/Direct/TxSpec.hs
  hydra-tx/src/Hydra/Tx/Commit.hs
Labels: bug :bug:

#1685 API: Full transaction in SnapshotConfirmed
  CHANGELOG.md
  hydra-cluster/bench/Bench/EndToEnd.hs
  hydra-cluster/src/Hydra/Cluster/Scenarios.hs
  hydra-cluster/test/Test/EndToEndSpec.hs
  hydra-node/golden/ReasonablySized (ServerOutput (Tx ConwayEra)).json
  hydra-node/golden/ReasonablySized (ServerOutput SimpleTx).json
  hydra-node/golden/ReasonablySized (TimedServerOutput (Tx ConwayEra)).json
  hydra-node/golden/ServerOutput/CommandFailed.json
  hydra-node/golden/ServerOutput/CommitApproved.json
  hydra-node/golden/ServerOutput/CommitFinalized.json
  hydra-node/golden/ServerOutput/CommitRecorded.json
  hydra-node/golden/ServerOutput/CommitRecovered.json
  hydra-node/golden/ServerOutput/Committed.json
  hydra-node/golden/ServerOutput/DecommitApproved.json
  hydra-node/golden/ServerOutput/DecommitFinalized.json
  hydra-node/golden/ServerOutput/DecommitInvalid.json
  hydra-node/golden/ServerOutput/DecommitRequested.json
  hydra-node/golden/ServerOutput/GetUTxOResponse.json
  hydra-node/golden/ServerOutput/Greetings.json
  hydra-node/golden/ServerOutput/HeadIsAborted.json
  hydra-node/golden/ServerOutput/HeadIsClosed.json
  hydra-node/golden/ServerOutput/HeadIsContested.json
  hydra-node/golden/ServerOutput/HeadIsFinalized.json
  hydra-node/golden/ServerOutput/HeadIsInitializing.json
  hydra-node/golden/ServerOutput/HeadIsOpen.json
  hydra-node/golden/ServerOutput/IgnoredHeadInitializing.json
  hydra-node/golden/ServerOutput/InvalidInput.json
  hydra-node/golden/ServerOutput/PeerConnected.json
  hydra-node/golden/ServerOutput/PeerDisconnected.json
  hydra-node/golden/ServerOutput/PeerHandshakeFailure.json
  hydra-node/golden/ServerOutput/PostTxOnChainFailed.json
  hydra-node/golden/ServerOutput/ReadyToFanout.json
  hydra-node/golden/ServerOutput/SnapshotConfirmed.json
  hydra-node/golden/ServerOutput/TxInvalid.json
  hydra-node/golden/ServerOutput/TxValid.json
  hydra-node/golden/StateChanged/PartySignedSnapshot.json
  hydra-node/golden/StateChanged/SnapshotConfirmed.json
  hydra-node/golden/StateChanged/SnapshotRequested.json
  hydra-node/hydra-node.cabal
  hydra-node/json-schemas/api.yaml
  hydra-node/src/Hydra/API/ServerOutput.hs
  hydra-node/src/Hydra/HeadLogic.hs
  hydra-node/src/Hydra/Logging/Monitoring.hs
  hydra-node/test/Hydra/API/ServerOutputSpec.hs
  hydra-node/test/Hydra/BehaviorSpec.hs
  hydra-node/test/Hydra/HeadLogicSpec.hs
  hydra-node/test/Hydra/Logging/MonitoringSpec.hs
  hydra-node/test/Hydra/Model.hs
  hydra-node/test/Hydra/NodeSpec.hs
  hydra-tx/src/Hydra/Tx/Snapshot.hs
  hydraw/static/bundle.js
Labels: task, api

#1694 Move / deduplicate genAbortableOutputs
  hydra-node/test/Hydra/Chain/Direct/TxSpec.hs
  hydra-tx/test/Hydra/Tx/Contract/Abort.hs
  hydra-tx/testlib/Test/Hydra/Tx/Gen.hs
Labels: tidying

#1696 Remove unused Commit client input
  CHANGELOG.md
  hydra-node/json-schemas/api.yaml
  hydra-node/json-schemas/logs.yaml
  hydra-node/src/Hydra/API/ClientInput.hs
Labels: follow-up

#1702 Re-use contestation period as a deposit deadline
  hydra-cluster/src/Hydra/Cluster/Scenarios.hs
  hydra-node/golden/ReasonablySized (TimedServerOutput (Tx ConwayEra)).json
  hydra-node/golden/ServerOutput/CommitRecorded.json
  hydra-node/json-schemas/api.yaml
  hydra-node/src/Hydra/API/HTTPServer.hs
  hydra-node/src/Hydra/API/Server.hs
  hydra-node/src/Hydra/API/ServerOutput.hs
  hydra-node/src/Hydra/HeadLogic.hs
  hydra-node/src/Hydra/Node/Run.hs
  hydra-node/test/Hydra/API/HTTPServerSpec.hs
  hydra-node/test/Hydra/API/ServerSpec.hs
  hydra-node/test/Hydra/BehaviorSpec.hs
Labels: follow-up

#1728 Update mithril to 2442.0
  CHANGELOG.md
  flake.lock
  flake.nix
Labels: bug :bug:
